### ISSUE TITLE
Github release script better handle descriptions

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform-release#1]
Any descriptions entered through github are overwritten and set to blank when re-releasing the same tag. We could

1. write the description in a file in the repo, so that the script sends it to github in our behalf or
2. do some more scripting so that if there is a description is set, we send it again when editing the release.

@rjmackay  what do you think would work best?

**Comment by rjmackay** [comment]
TBH I'd prefer a combination of both
1. If description is set, don't overwrite it
2. If description is not set, we send the annotation text from the git tag. Ideally taking line 1 => title

**Comment by rjmackay** [comment]
Solved this the easy way: just don't edit the release if it exists. I *think* that should work alright.
