### ISSUE TITLE
Each() function deprecated

### ISSUE THREAD

**Issue by norlab** [ushahidi/platform-release#10]
When performing the database migration I get:

"status": "Deprecated",
            "title": "The each() function is deprecated. This message will be suppressed on further calls",
            "message": "The each() function is deprecated. This message will be suppressed on further calls",
            "class": "ErrorException",
            "file": "/var/www/html/platform/vendor/aura/di/src/Factory.php",
            "line": 622,

**Comment by tuxpiper** [comment]
Yep unfortunately things don't quite yet run on PHP 7.2 . However this is an issue to address in https://github.com/ushahidi/platform . We won't fix it here.

**Comment by tuxpiper** [comment]
Just a note that the upcoming release will be using Aura 3.4 . Support for PHP 7.2 is looking good.
