### ISSUE TITLE
Initialize the Wiki Page 

### ISSUE THREAD

**Issue by allamiro** [ushahidi/platform-release#17]
Wiki page is not activated to allow contributors to add tutorials how to to the community  .

**Comment by tuxpiper** [comment]
@allamiro We are pretty soon going to open an avenue for community to collaborate on documentation. Stay tuned!

**Comment by tuxpiper** [comment]
documentation is concentrated now in the developer and contributor documentation home: https://docs.ushahidi.com/platform-developer-documentation/
