### ISSUE TITLE
Bug After Installing Ushahidi Platform

### ISSUE THREAD

**Issue by allamiro** [ushahidi/platform-release#18]
After installing Ushahidi admin account  can not change the settings 
The resolution that Khalid Elshafie found is to login to the MySQL database and update the admin roles
using the following SQL statement

**Comment by ganeshgk** [comment]
Which SQL statement? Seems you haven't updated the issue with the SQL statement.

**Comment by tuxpiper** [comment]
Haven't been able to reproduce this the couple times I have tried. Closing for now.
