### ISSUE TITLE
ushahidi-platform-release-v4.4.1.tar.gz check permissions on untar?

### ISSUE THREAD

**Issue by ruralhuman** [ushahidi/platform-release#26]
I had the some permissions issue and fails when unzipping the file on the centos host. So I tried to unpack the file on windows/7-zip to get rid of permissions as a workaround.

Got this error. Might not be a big issue. 
![image](https://user-images.githubusercontent.com/52637132/77479402-00398580-6e20-11ea-81bb-3dddac021394.png)

**Comment by justweekend** [comment]
Can i take this bug?
