### ISSUE TITLE
The deployment does not have the necessary configuration to be added into the app

### ISSUE THREAD

**Issue by Kenji-K** [ushahidi/platform-release#4]
I have tried to deploy the Docker version of the platform, and attempted to connect the android app to it, but I get the message in the title. I assume it's because I haven't set the config.json up, but where and how do I set it up?

**Comment by lorinivalerio** [comment]
Hi Kenji-K, did you get any further info? I am in a similar situation, platform-api on vagrant and platform-client on a hosted server. I tried to place the config.json file I found on ushahidi support page almost everywhere I thought it could go, but no luck. I even tried to re-run gulp etc.

**Comment by saheleasy** [comment]
same problem is any luck ???

**Comment by simmytruong** [comment]
hi,
Do you have any update on this? 

I tried to work with apache setup 
Alias /config.json /var/www/html/platform/httpdocs/config.json
I can download the config.json but when login, it displays an issue

![issue](https://user-images.githubusercontent.com/35060602/46254821-74130000-c4bf-11e8-8b5c-42df7b252917.png)

**Comment by tuxpiper** [comment]
@simmytruong  The last commit I just pushed provides examples on how to set this up for nginx and apache , look under the dist/ folder 

The release bundles for v4.0.0 onwards will contain these configurations as well
