### ISSUE TITLE
Uploaded Images not showing up in 3.7

### ISSUE THREAD

**Issue by diegodorgam** [ushahidi/platform-release#5]
I've found this bug, but still can't find a solution, I've found other users with the same problems
[foruns](https://forums.ushahidi.com/t/uploaded-images-not-showing-up-on-ushahidi-3/4178/11)
And basically, the images are inside the right upload folder, in `/var/www/html/platform/application/media/uploads/` with chmod 777 all over, but when we try to access it trough URL it returns a blank screen.

This is happening in Image fields and logo, it seems that ushahidi can't find image files.

I'm running with NGINX confs:
```
server {
        listen *:80 default_server;

        #
        root /var/www/html;

        # Force encoding.
        charset utf-8;
        override_charset on;

        location /platform {
                fastcgi_param   QUERY_STRING            $query_string;
                fastcgi_param   REQUEST_METHOD          $request_method;
                fastcgi_param   CONTENT_TYPE            $content_type;
                fastcgi_param   CONTENT_LENGTH          $content_length;

                fastcgi_split_path_info         ^(/platform/)(.*)$;

                fastcgi_param   SCRIPT_FILENAME         $document_root/platform/httpdocs/index.php;
                fastcgi_param   SCRIPT_NAME             $fastcgi_script_name;
                fastcgi_param   PATH_INFO               $fastcgi_path_info;
                fastcgi_param   PATH_TRANSLATED         $document_root$fastcgi_path_info;
                fastcgi_param   REQUEST_URI             $request_uri;
               fastcgi_param   DOCUMENT_URI            $document_uri;
                fastcgi_param   DOCUMENT_ROOT           $document_root;
                fastcgi_param   SERVER_PROTOCOL         $server_protocol;

                fastcgi_param   GATEWAY_INTERFACE       CGI/1.1;
                fastcgi_param   SERVER_SOFTWARE         nginx/$nginx_version;

                fastcgi_param   REMOTE_ADDR             $remote_addr;
                fastcgi_param   REMOTE_PORT             $remote_port;
                fastcgi_param   SERVER_ADDR             $server_addr;
                fastcgi_param   SERVER_PORT             $server_port;
                fastcgi_param   SERVER_NAME             $server_name;

                fastcgi_param   HTTPS                   $https;

                fastcgi_pass    localhost:9000;
                fastcgi_pass_header Authorization;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }
}
```

Just like this repository file, but I've changed the location:
```
        location / {
                try_files $uri $uri/ /index.html;
        }
```

In a hope to fix the problem, according to NGINX documentation for Angular (https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode) given by @tuxpiper in the community foruns... 

thks for any help, I'm really needing it....

**Comment by diegodorgam** [comment]
I think I fund something related to the API, but I'm not sure how this works...
when I try to upload an image for header in configs, the path is stored in database config table as `http://mapa.tonarede.org.br/media/upload...` and when I try this URL in browser, it returns a blank page.
And then I found out that my API is set to this same domain:

```
{
    "count": 3,
    "results": [
        {
            "id": "features",
            "url": "http://mapa.tonarede.org.br/api/v3/config/features",
            "views": {
                "map": true,
                "list": true,
                "chart": true,
                "timeline": true,
                "activity": true,
                "plan": false
            },...
```

but in both cases I can't access /media or /api unless I add /platform first. And I'm running under https also, so when I change the URL to https://mapa.tonarede.org.br/platform/media/upload... it returns the image, or when I use https://mapa.tonarede.org.br/platform/api... it returns it working fine.

So I guess it's a problem in the API backend configuration.

Any thoughts in what could I do to change it? 

thks in advance

**Comment by diegodorgam** [comment]
Guys, @tuxpiper , any ideas on this?

**Comment by tuxpiper** [comment]
@diegodorgam 

since you seem to be running the API in a subfolder of the domain , I would recommend to edit application/config/init.php and set `'base_url' => '/platform'`

Hope this helps!

**Comment by diegodorgam** [comment]
It worked @tuxpiper !

Very very thanks!

**Comment by DomPires1** [comment]
I'm having the same problem. My images are not showing up, when I try to refresh the page http://txeka.co/views/map give me an error. I tried the solutions I found here but they did not work. Help me please

**Comment by tuxpiper** [comment]
@DomPires1 you seem to have a different problem. When I load http://txeca.co/views/map I get a 500 error from the server. Could you please look in apache's error.log for relevant log entries and forward them to our community channel in https://gitter.im/ushahidi/Community ?

**Comment by DomPires1** [comment]
@tuxpiper I already solved this erro. I had to http://app.txeka.co/views/map. **Romina Suarez** told to change my nodejs version to 6.9.2 and I changed but it still does not show photos and now upload does not accept and I already gave the following permission> sudo chmod 0777 application/logs application/cache application/media /uploads

my server> server.txeka.co server.txeka.co/api/v3/config
my app> app.txeka.co - I just changed the nameserver on the virtualhost
