### ISSUE TITLE
Can't connect database if it isn't in localhost

### ISSUE THREAD

**Issue by lupa18** [ushahidi/platform-release#6]
I'm trying to install U 3.x using your tutorial. In my case, the database is in a separate host. 
When I try to make migrations I got a "can't" connect error. 

I fixed editing by hand your parameters in phinx.php and putting my own values, ie: 
host: myhost (instead of variable you put there)
database: mydb (idem)

I double checked .env file and values are correct.

**Comment by lupa18** [comment]
After installation, I can't use it because similar error: can't connect to database. It tries to connect: 
`Access denied for user ''@'172.17.0.11' (using password: NO)`

instead of mysuer@myhost (with password). 

is it possible that .env file doesn't loaddng ?

**Comment by rjmackay** [comment]
How are you running the migrations? Which directory are you running them from?

**Comment by lupa18** [comment]
I'm working with database in a separate host. 
**1.** I go to the right folder, ie: platform

**2.** I run ./bin/phinx migrate -c application/phinx.php

it works, but database doesn't connect. 

**3.** then, I edit that phinx.php file and hardcoded my credentials, as I said above and repeat step 2 and migrations works perfect. 

**4.** Then I tried to access platform (by the url) and got the connection error described in second comment above.

I think, for some reason, the .env file is not loading or something like that. 

When I run a command with mysql-client to external database it works, so there is not a network problem.

**Comment by lupa18** [comment]
Confirmed. There is an error on host and password environment variables. Something in the way to read them in database.php fails. 

So I hardcoded them there and now Ushahidi is working :smile: 
 
Saddly I'm not php expert and can't make a PR to solve it.

**Comment by lupa18** [comment]
Someone could test install this software in separate machines?

**Comment by tuxpiper** [comment]
We routinely use separate machines as databases here. I think this may have been a confusion with environment variable naming as we transitioned from Kohana to Lumen.

I'm closing by now, this is game to be reopened if it can be replicated with the current version.
