### ISSUE TITLE
Can run in subdirectory as loading of config.js and .css files fails

### ISSUE THREAD

**Issue by poVoq** [ushahidi/platform-release#8]
Probably a rather easy fix, but I can't get my Nginx to properly load the config.js and the .css files requested by the index.html.

The setup I am trying to get working is that the html directory is not in the root of the webserver, but rather is the /ushahidi subfolder, so that https://mydomain.com/ushahidi loads the index.html file.

This works fine so far, however I only get the "Sorry, something went wrong. Try reloading the page." message as the browser tries to load the config.js etc. files from https://mydomain.com/confg.js instead of https://mydomain.com/ushahidi/config.js as it should.

Thanks for the help :smile:

**Comment by tuxpiper** [comment]
It's always been tricky but now there are additional problems around running the Lumen API (v4.0.0) under a domain "subdirectory" .

I am afraid we are not going to be able to support doing that in the future.

**Comment by poVoq** [comment]
Ok, understandable. I have also switched to a sub-domain (& Docker) based system now. So lets close this, I guess.
